### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mayel** [stephanediondev/feed#2]
Having trouble getting up and running with Docker, install fails when trying to install elastisearch. I tried changing the Dockerfile version from latest to 2, and that helped, but then still getting this error:

`Verifying https://github.com/royrusso/elasticsearch-HQ/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [hq] is a site plugin but has no '_site/' directory
ERROR: Service 'rs_elasticsearch' failed to build`

**Comment by project29k** [comment]
In /docker/elasticsearch/Dockerfile, you can remove the 3 lines related to the plugins installation

There are big changes with ElasticSearch:
- with version 5, "site plugins" are no longer supported
https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/intro.html
- with version 6, mapping types are removed, the current code to use ElasticSearch doesn't work
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

I have to upgrade and move to one index by type
